import Head from 'next/head';
import Hero from '../components/Hero3';
import Clients from '../components/Clients';
import React, { useState, useEffect } from 'react';
import Footer from '../components/Footer';
import CTA from '../components/CTA';
import Card from '../components/Card';
import { getDataFromWebsite } from '../lib/api';

export default function Properties() {

  const [apiProperties, setApiProperties] = useState([]); // for api implementation https://dev.to/alais29/building-a-real-time-search-filter-in-react-a-step-by-step-guide-3lmm

  let properties = [
    {name: "Embassy Tech Square", location: "Outer Ring Road, Bangalore", area: "84,512", pricesqf: "13,253", yeild: "8.62", returntarget: "15.9", img: "https://propmedia1.propertyshare.in/website/property/d3Joby9VTnlncndkZit1ZlAxQ2ZMdz09/media-v2/images/listingbanner/540x420/1638176089-embassy-tech-square-bangalore-1.jpg"},
    {name: "Lodha iThink", location: "Thane , Mumbai", area: "35,802", pricesqf: "10,000", yeild: "8.44", returntarget: "15", img: "https://propmedia1.propertyshare.in/website/property/Mm1rMWthZHN1V0x3ejlWQlN5TmJCUT09/media-v2/images/listingbanner/540x420/1631124574-lodha-ithink-mumbai-1.jpg"},
  ]

  const [searchItem, setSearchItem] = useState('');
  const [filteredProperties, setFilteredProperties] = useState([]);

  useEffect(() => {

    getDataFromWebsite().then(res => res.json())
      .then(data => {
        setApiProperties(data)
        setFilteredProperties(data)
      })

  }, [])

  console.log(apiProperties)



  const handleInputChange = (e) => {
    const searchTerm = e.target.value;
    setSearchItem(searchTerm)

    const filteredItems = apiProperties.filter((property) =>
      property.text.toLowerCase().includes(searchTerm.toLowerCase())
    );
    setFilteredProperties(filteredItems);
  }


  return (
    <div>

      <Head>
        <title>PropertyVerse</title>
        <meta name='description' content='Generated by create next app' />
        <link rel='icon' href='/favicon.ico' />
      </Head>
      <Hero message='Welcome to a redefinition of property management. Discover seamless solutions for property owners and tenants alike' />


      <div className='my-16'>
        {/* <h1 className='font-sans text-center text-4xl my-10 text-gray-500'>All Properties</h1> */}
        <div className="mx-7 max-w-xs">
          <label className="block text-gray-400 text-sm font-bold mb-2">
            Search For Properties
          </label>
          <input className="shadow appearance-none bg-transparent rounded w-full py-2 px-3 text-gray-200 leading-tight outline-none focus-ring-dark  " id="search" type="text" value={searchItem} onChange={handleInputChange} placeholder="Type to Search" />
        </div>
        <br />
        <div className="grid grid-cols-1  gap-4 sm:gap-0 md:grid-cols-2 lg:grid-cols-4">
          {(filteredProperties.length == 0) ?
            <div role="status" className='ml-12' >
              <svg aria-hidden="true" className="inline w-8 h-8 text-gray-200 animate-spin dark:text-gray-600 fill-red-600" viewBox="0 0 100 101" fill="none" xmlns="http://www.w3.org/2000/svg">
                <path d="M100 50.5908C100 78.2051 77.6142 100.591 50 100.591C22.3858 100.591 0 78.2051 0 50.5908C0 22.9766 22.3858 0.59082 50 0.59082C77.6142 0.59082 100 22.9766 100 50.5908ZM9.08144 50.5908C9.08144 73.1895 27.4013 91.5094 50 91.5094C72.5987 91.5094 90.9186 73.1895 90.9186 50.5908C90.9186 27.9921 72.5987 9.67226 50 9.67226C27.4013 9.67226 9.08144 27.9921 9.08144 50.5908Z" fill="currentColor" />
                <path d="M93.9676 39.0409C96.393 38.4038 97.8624 35.9116 97.0079 33.5539C95.2932 28.8227 92.871 24.3692 89.8167 20.348C85.8452 15.1192 80.8826 10.7238 75.2124 7.41289C69.5422 4.10194 63.2754 1.94025 56.7698 1.05124C51.7666 0.367541 46.6976 0.446843 41.7345 1.27873C39.2613 1.69328 37.813 4.19778 38.4501 6.62326C39.0873 9.04874 41.5694 10.4717 44.0505 10.1071C47.8511 9.54855 51.7191 9.52689 55.5402 10.0491C60.8642 10.7766 65.9928 12.5457 70.6331 15.2552C75.2735 17.9648 79.3347 21.5619 82.5849 25.841C84.9175 28.9121 86.7997 32.2913 88.1811 35.8758C89.083 38.2158 91.5421 39.6781 93.9676 39.0409Z" fill="currentFill" />
              </svg>
              <p className=" text-gray-300 sr-only">Loading...</p>
            </div>
            : <></>}
          {filteredProperties.map(property => <div key={property.text} className="p-4 text-center sm:p-0"><Card name={property.text} location={property.location}  img={property.imageSrc} /></div>)}
        </div>
      </div>


      <div className='section6'>
        <Footer />
      </div>
    </div>
  );
}

