import Head from 'next/head';
import React, { useState, useEffect } from 'react';
import { Typography } from '@material-tailwind/react';
import Footer from '../components/Footer';
import Image from 'next/image';
import BlogContext from '../components/BlogContext';

export default function Blog() {

    return (
        <div>

            <Head>
                <title>PropertyVerse</title>
                <meta name='description' content='Generated by create next app' />
                <link rel='icon' href='/favicon.ico' />
            </Head>
            <section className='my-36' style={{ minHeight: "100vh" }}>
                <Typography className='p-10' variant='h1'>Blogs</Typography>
                <hr className='my-6 line' />
                <div className="grid">

                    <BlogContext heading={"Heading"} date={"Aug 6th, 2023"} subheading={"this is a subheading"} description={"Lorem ipsum dolor sit amet consectetur adipisicing elit. Sed labore dignissimos ipsam, accusantium ea amet provident aperiam ipsa non illum, nobis ut cumque tenetur suscipit hic repudiandae quisquam blanditiis neque?s"} />
                    <BlogContext heading={"Heading"} date={"Aug 6th, 2023"} subheading={"this is a subheading"} description={"Lorem ipsum dolor sit amet consectetur adipisicing elit. Sed labore dignissimos ipsam, accusantium ea amet provident aperiam ipsa non illum, nobis ut cumque tenetur suscipit hic repudiandae quisquam blanditiis neque?s"} />
                    <BlogContext heading={"Heading"} date={"Aug 6th, 2023"} subheading={"this is a subheading"} description={"Lorem ipsum dolor sit amet consectetur adipisicing elit. Sed labore dignissimos ipsam, accusantium ea amet provident aperiam ipsa non illum, nobis ut cumque tenetur suscipit hic repudiandae quisquam blanditiis neque?s"} />


                </div>
            </section>


            <div className='section6'>
                <Footer />
            </div>
        </div>
    );
}



