import Head from 'next/head';
import React, { useState, useEffect } from 'react';
import { Typography } from '@material-tailwind/react';
import Footer from '../components/Footer';
import Script from 'next/script';
import BlogContext from '../components/BlogContext';
import { createClient } from 'contentful';

export async function getStaticProps() {
    const client = createClient({
        space: process.env.NEXT_PUBLIC_CONTENTFUL_SPACE_ID,
        accessToken: process.env.NEXT_PUBLIC_CONTENTFUL_ACCESS_TOKEN,
    });

    const res = await client.getEntries({ content_type: 'PropertyVerse' });

    return {
        props: {
            blogs: res.items,
        },
        revalidate: 60
    }
}

export default function Blog({ blogs }) {

    let schema = {
        "@context": "https://schema.org/",
        "@type": "WebSite",
        "name": "Property Verse",
        "url": "https://www.propertyverse.co.in/",
        "potentialAction": {
            "@type": "SearchAction",
            "target": "https://www.propertyverse.co.in/{search_term_string}",
            "query-input": "required name=search_term_string"
        }
    }

    const { title, slug, thumbnail, content, date } = blogs[0].fields

    return (
        <div>
            <Script
                type='application/ld+json'
                dangerouslySetInnerHTML={{ __html: JSON.stringify(schema) }} />
            <Head>
                <title>Blogs</title>
                <meta name='description' content='Generated by create next app' />
                <link rel='icon' href='/favicon.ico' />
            </Head>
            <section className='my-36' style={{ minHeight: "100vh" }}>
                <Typography className='p-10' variant='h1'>Blogs</Typography>
                <hr className='my-6 line' />
                <div className="grid">
                    {
                        blogs.map(blog => (
                            <div key={blog.sys.id}><BlogContext img={blog.fields.thumbnail} details={blog} />
                            </div>
                        ))
                    }

                </div>
            </section>


            <div className='section6'>
                <Footer />
            </div>
        </div>
    );
}



