import Head from 'next/head';
import Hero from '../components/Hero';
import Clients from '../components/Clients';
import Footer from '../components/Footer';
import CTA from '../components/CTA';
import Section from '../components/Info';
import Card from '../components/Card';


export default function Home() {
  return (
    <div className='darkgradient'>
      <Head>
        <title>PropertyVerse</title>
        <meta name='description' content='Generated by create next app' />
        <link rel='icon' href='/favicon.ico' />
      </Head>
      <Hero message='Welcome to a redefinition of property management. Discover seamless solutions for property owners and tenants alike' />
      <div data-aos-duration="1000" data-aos="fade-down" data-aos-delay="300"  className="section1">
        <Section />
      </div>
      <div className="section2" id="section2">
        <Clients />
      </div>
       <div className="section5">
        <CTA />
      </div>

      <div className='section6'>
        <Footer />
      </div>
    </div>
  );
}

