import Head from 'next/head';
import Image from 'next/image';
import Hero from '../components/Hero';
import Footer from '../components/Footer';
import Slider from '../components/Slider';
import { SliderData } from '../components/SliderData';
import Card from '../components/Card';
import { FaDrawPolygon } from 'react-icons/fa';

export default function Home() {
  return (
    <div className=''>
      <Head>
        <title>Photography Next App</title>
        <meta name='description' content='Generated by create next app' />
        <link rel='icon' href='/favicon.ico' />
      </Head>
      <Hero heading='Property Verse' message='Invest in real estate' />
      <div className='section1'>
        <h1 className='font-sans text-center text-4xl'>All Properties</h1>
        <div className="flex mb-4 p-10 card-section flex-wrap">
          <Card />
          <Card />
          <Card />
        </div>

      </div>
      <div className='section2'>
        <h1 className='font-sans text-center text-4xl py-10'>Our Clients</h1>
        <div className="flex">
          <div className="w-1/4 logo">
            logo<br /> PropertyShare
          </div>
          <div className="w-1/4 logo">Wisex</div>
          <div className="w-1/4 logo">HBits</div>
          <div className="w-1/4 logo">Assetmonk</div>
        </div>
      </div>
      <div className='section3'>
        <div className="2xl:container 2xl:mx-auto md:py-12 lg:px-20 md:px-6 py-9 px-4">
          {/* <!--- more free and premium Tailwind CSS components at https://tailwinduikit.com/ ---> */}
          <div className="mt-4 flex md:justify-between md:items-start md:flex-row flex-col justify-start items-start">

            <section className="dark:bg-gray-800 dark:text-gray-100">
              <div className="container flex flex-col justify-center px-4 py-8 mx-auto md:p-8">
                <h2 className="text-2xl font-semibold sm:text-4xl">Frequently Asked Questions</h2>
                <p className="mt-4 mb-8 dark:text-gray-400">Sagittis tempor donec id vestibulum viverra. Neque condimentum primis orci at lacus amet bibendum.</p>
                <div className="space-y-4">
                  <details className="w-full border rounded-lg">
                    <summary className="px-4 py-6 focus:outline-none focus-visible:ri">Ex orci laoreet egestas sapien magna egestas scelerisque?</summary>
                    <p className="px-4 py-6 pt-0 ml-4 -mt-4 dark:text-gray-400">Lectus iaculis orci metus vitae ligula dictum per. Nisl per nullam taciti at adipiscing est. </p>
                  </details>
                  <details className="w-full border rounded-lg">
                    <summary className="px-4 py-6 focus:outline-none focus-visible:ri">Lorem at arcu rutrum viverra metus sapien venenatis lobortis odio?</summary>
                    <p className="px-4 py-6 pt-0 ml-4 -mt-4 dark:text-gray-400">Tincidunt ut hac condimentum rhoncus phasellus nostra. Magna porttitor egestas tincidunt neque vehicula potenti. </p>
                  </details>
                  <details className="w-full border rounded-lg">
                    <summary className="px-4 py-6 focus:outline-none focus-visible:ri">Eleifend feugiat sollicitudin laoreet adipiscing bibendum suscipit erat?</summary>
                    <p className="px-4 py-6 pt-0 ml-4 -mt-4 dark:text-gray-400">Justo libero tellus integer tincidunt justo semper consequat venenatis aliquet imperdiet. Ultricies urna proin fusce nulla pretium sodales vel magna et massa euismod vulputate sed. </p>
                  </details>
                </div>
              </div>
            </section>
          </div>
          
        </div>
      </div>

      <div className='section4'>
        <Footer />
      </div>
    </div>
  );
}

