import Head from 'next/head';
import Hero from '../components/Hero3';
import Clients from '../components/Clients';
import Footer from '../components/Footer';
import CTA from '../components/CTA';
import Section from '../components/Info';
import Card from '../components/Card';

export default function Home() {
  return (
    <div className=''>
      <Head>
        <title>PropertyVerse</title>
        <meta name='description' content='Generated by create next app' />
        <link rel='icon' href='/favicon.ico' />
      </Head>
      <Hero message='Welcome to a redefinition of property management. Discover seamless solutions for property owners and tenants alike' />

     
      <div className='section4 my-16'>
        {/* <h1 className='font-sans text-center text-4xl my-10 text-gray-500'>All Properties</h1> */}
        <br />
        <div className="grid grid-cols-1 gap-4 md:grid-cols-2 lg:grid-cols-4">
          <div className="p-4 text-center md:p-1"><Card redirectUrl={'/info/work'} /></div>
          <div className="p-4 text-center md:p-1"><Card redirectUrl={'/info/work'} /></div>
          <div className="p-4 text-center md:p-1"><Card redirectUrl={'/info/work'} /></div>
          <div className="p-4 text-center md:p-1"><Card redirectUrl={'/info/work'} /></div>
        </div>
      </div>


      <div className='section6'>
        <Footer />
      </div>
    </div>
  );
}

