import Head from 'next/head';
import React, { useState, useEffect } from 'react';
import { Typography } from '@material-tailwind/react';
import Footer from '../../components/Footer';
import Image from 'next/image';

export default function Blog() {

    return (
        <div>

            <Head>
                <title>Blog 1</title>
                <meta name='description' content='Generated by create next app' />
                <link rel='icon' href='/favicon.ico' />
            </Head>
            <section className='my-36 lg:mx-24 md:mx-14 mx-2' style={{ minHeight: "100vh" }}>
                <Typography className='text-center font-bold'>Aug 6th, 2023</Typography>
                <Typography className='text-2xl text-center text-gray-400'>Lorem ipsum dolor sit amet.</Typography>
                <hr className='my-5 lg:mx-24 md:mx-14 mx-2 line' />

                <div className="lg:mx-24 md:mx-14 mx-2 my-10">
                    <Image objectFit='cover' layout='responsive' height={35} width={100} src="https://images.unsplash.com/photo-1471039497385-b6d6ba609f9c?q=80&w=2070&auto=format&fit=crop&ixlib=rb-4.0.3&ixid=M3wxMjA3fDB8MHxwaG90by1wYWdlfHx8fGVufDB8fHx8fA%3D%3D" />
                </div>
                <Typography className='lg:ml-24 md:ml-14 ml-2 text-red-400' variant='h3'>Introduction</Typography>
                <br />
                <br />
                <Typography className='leading-loose lg:mx-24 md:mx-14 mx-2 text-gray-400'>
                    Lorem ipsum dolor sit amet consectetur adipisicing elit. Dolorem in, nam, ratione ipsam repellat, culpa quasi incidunt perferendis corrupti autem quo! Quos autem, minima quibusdam pariatur nobis illum ea accusamus cumque! Dolorem, voluptas. Fugiat deserunt velit ducimus illum quaerat. Quam eveniet voluptatum deleniti eligendi quae delectus quas nemo dolorem, perferendis recusandae architecto consequatur commodi earum placeat dicta odio iure sint quos fugiat nulla ipsum optio molestias, numquam quod! Suscipit molestiae quaerat numquam enim deleniti asperiores voluptas nisi temporibus, ullam animi fugit iste ipsa dolores aperiam molestias. Consectetur, molestias? Libero architecto omnis suscipit repellendus saepe velit rerum totam nulla. Rem beatae recusandae culpa inventore, deleniti a repudiandae sed, nemo natus, illo voluptates tempora ratione? Sint ipsa accusantium saepe nostrum voluptates soluta, rerum ea neque tenetur reiciendis. Eaque, animi eum. Maiores quidem harum reiciendis, velit pariatur quas maxime repudiandae neque, laborum temporibus est odio. Possimus fuga sint quis, veritatis soluta dicta esse unde provident eos minus corporis beatae hic consequatur earum adipisci, necessitatibus tempore! Iusto, esse delectus et aut est laborum eveniet, quasi quis temporibus ipsam tempora, maxime ipsum praesentium. Earum odit nisi aspernatur maxime, autem voluptatem mollitia veniam dolor laboriosam optio quisquam tenetur exercitationem consectetur vero animi distinctio fugiat commodi repellendus.
                </Typography>
                <br />
                <Typography className='leading-loose lg:mx-24 md:mx-14 mx-2 text-gray-400'>
                    Lorem ipsum dolor sit amet consectetur adipisicing elit. Dolorem in, nam, ratione ipsam repellat, culpa quasi incidunt perferendis corrupti autem quo! Quos autem, minima quibusdam pariatur nobis illum ea accusamus cumque! Dolorem, voluptas. Fugiat deserunt velit ducimus illum quaerat. Quam eveniet voluptatum deleniti eligendi quae delectus quas nemo dolorem, perferendis recusandae architecto consequatur commodi earum placeat dicta odio iure sint quos fugiat nulla ipsum optio molestias, numquam quod! Suscipit molestiae quaerat numquam enim deleniti asperiores voluptas nisi temporibus, ullam animi fugit iste ipsa dolores aperiam molestias. Consectetur, molestias? Libero architecto omnis suscipit repellendus saepe velit rerum totam nulla. Rem beatae recusandae culpa inventore, deleniti a repudiandae sed, nemo natus, illo voluptates tempora ratione? Sint ipsa accusantium saepe nostrum voluptates soluta, rerum ea neque tenetur reiciendis. Eaque, animi eum. Maiores quidem harum reiciendis, velit pariatur quas maxime repudiandae neque, laborum temporibus est odio. Possimus fuga sint quis, veritatis soluta dicta esse unde provident eos minus corporis beatae hic consequatur earum adipisci, necessitatibus tempore! Iusto, esse delectus et aut est laborum eveniet, quasi quis temporibus ipsam tempora, maxime ipsum praesentium. Earum odit nisi aspernatur maxime, autem voluptatem mollitia veniam dolor laboriosam optio quisquam tenetur exercitationem consectetur vero animi distinctio fugiat commodi repellendus.
                </Typography>

            </section>
            <div className='section6'>
                <Footer />
            </div>
        </div>
    );
}



