import React, { useEffect, useState } from 'react'
import TenantDetails from '../../components/TenantDetails';
import CapitalAppreciation from '../../components/CapitalAppreciation';
import MyModal from '../../components/Dialog';
import { Typography } from "@material-tailwind/react";
import Carousel from '../../components/VillaCarousel';
import Hero2 from '../../components/Hero2';
import MyChart from '../../components/MyChart';
import Head from 'next/head';
import Image from 'next/image';
import Footer from '../../components/Footer'

export default function Details() {

    const [value, setValue] = useState(1000000);
    const [loaded, setLoaded] = useState("animate-pulse");

    const images = [
        'https://storage.googleapis.com/sharenest/properties/Villa%20ANANYATA/01%20(1)-min.jpg',
        'https://storage.googleapis.com/sharenest/properties/Villa%20ANANYATA/01-min.jpg',
        'https://storage.googleapis.com/sharenest/properties/Villa%20ANANYATA/01DWD-min.jpg',
        'https://storage.googleapis.com/sharenest/properties/Villa%20ANANYATA/01_CShading_LightMix-min.jpg',
        'https://storage.googleapis.com/sharenest/properties/Villa%20ANANYATA/02%20(1)-min.jpg',
        'https://storage.googleapis.com/sharenest/properties/Villa%20ANANYATA/02-min.jpg',
        'https://storage.googleapis.com/sharenest/properties/Villa%20ANANYATA/03-min.jpg',
        'https://storage.googleapis.com/sharenest/properties/Villa%20ANANYATA/03ERUAJT-min.jpg',
        'https://storage.googleapis.com/sharenest/properties/Villa%20ANANYATA/04%20(1)-min.jpg',
        'https://storage.googleapis.com/sharenest/properties/Villa%20ANANYATA/04-min.jpg',
        'https://storage.googleapis.com/sharenest/properties/Villa%20ANANYATA/BD%20VIEW%203.jpg',
        'https://storage.googleapis.com/sharenest/properties/Villa%20ANANYATA/BEDROOM%20SIDE%20VIEW-min.jpg',
        'https://storage.googleapis.com/sharenest/properties/Villa%20ANANYATA/ERGUV-min.jpg',
        'https://storage.googleapis.com/sharenest/properties/Villa%20ANANYATA/KITCHEN2407%20PSD-min.jpg',
        'https://storage.googleapis.com/sharenest/properties/Villa%20ANANYATA/ONLY%20CHAIR-min.jpg',
        'https://storage.googleapis.com/sharenest/properties/Villa%20ANANYATA/PS1-min.jpg',
        'https://storage.googleapis.com/sharenest/properties/Villa%20ANANYATA/VIEW%202%20DRM.jpg',
        'https://storage.googleapis.com/sharenest/properties/Villa%20ANANYATA/VIEW%20BD%201-min.jpg',
        'https://storage.googleapis.com/sharenest/properties/Villa%20ANANYATA/WhatsApp%20Image%202023-02-17%20at%201.34.59%20PM-min.jpeg',
        'https://storage.googleapis.com/sharenest/properties/Villa%20ANANYATA/bar%20pps-min.jpg',
        'https://storage.googleapis.com/sharenest/properties/Villa%20ANANYATA/psd%20kitchen%202-min.jpg'
    ]

    const capitalappreciation = 10;

    const yr = ["6,16,59,908", "5,66,58,703", "5,91,52,456", "6,17,58,607", "6,44,81,911"]
    const prprtyname = "Villa Ananyata", invamt = "69,90,00,000", mr = "42,67,814", pmf = "5,82,500", tds = "4,74,202"
    const details = {
        rentalyeild: 9.14,
        returns: 18,
        price: "12,338",
        location: "ORR",
        name: "Aurbis Business Park",
        country: "Singapore",
        description: "Singapore-based Aurbis is a managed offices provider backed by Avila Capital which was founded by the Chairman of Assetz Property Group Singapore",
        start: "01 Oct 2019",
        lockinperiod: 5,
        enddate: "30 Sep 2029",
        totalarea: "52,277",
        rentpersf: 89,
        leaseperiod: 10,
        escalation: 4.5
    }


    const onUpdate = (e) => {
        setValue(Number(e.target.value));
    }

    return (

        <div>
            <Head>
                <title>{prprtyname}</title>
                <meta name='description' content='Generated by create next app' />
                <link rel='icon' href='/favicon.ico' />
            </Head>
            <Hero2 heading={prprtyname} message='' imageurl={'https://propmedia1.propertyshare.in/website/property/YXgrbVI5NXJabk9IbFNHbkIzRmlqQT09/media-v2/images/banner/1440x300/1601270009-the-pavilion-iii-bangalore-1.jpg'} />
            <div className='section1 text-gray-400'>
                <div className="flex md:flex-row  flex-wrap">

                    <div className="w-full p-4 text-center" style={{ minHeight: "5" }}>

                        <Carousel images={images} />
                    </div>


                </div>
                <br />
                <div>
                    <h1 className='font-sans text-4xl mx-10 py-10'>Investment Returns</h1>
                    <h1 className='text-2xl mx-10' >Investment Amount:  <span className='bg-gray-500 p-2 ml-2 text-gray-900'>₹ {invamt}</span></h1>
                    <div className="lg:w-3/4 my-72 p-4 rounded overflow-hidden shadow-lg shadow-gray-600 card">
                        <div className="px-0 md:px-6 py-4">
                            <div className="font-bold text-xl mb-2">Monthly Cash Flow</div>
                            <br />
                            <div className="overflow-hidden h-4 mb-4 text-xs flex rounded bg-emerald-200">
                                <div style={{ width: "50%" }} className="shadow-none flex flex-col text-center whitespace-nowrap text-white justify-center bg-red-500"></div>
                                <div style={{ width: "40%" }} className="shadow-none flex flex-col text-center whitespace-nowrap text-white justify-center bg-orange-500"></div>
                                <div style={{ width: "10%" }} className="shadow-none flex flex-col text-center whitespace-nowrap text-white justify-center bg-gray-500"></div>
                            </div>
                            <div className="mb-2 flex items-center justify-between gap-4 overflow-auto">
                                <Typography>
                                    MonthlyRent:<br /> <span className='text-gray-300 font-extrabold'>₹ {mr}</span>
                                </Typography>
                                <Typography>
                                    Property Management Fee: <br /> <span className='text-gray-300 font-extrabold'>₹ {pmf}</span>
                                </Typography>
                                <Typography>
                                    10% TDS: <br /> <span className='text-gray-300 font-extrabold'>₹ {tds}</span>
                                </Typography>
                            </div>

                            <div className="mb-2 flex items-center justify-between gap-4">
                            </div>



                        </div>
                    </div>
                    <div className="lg:w-3/4 px-6 py-4 ">
                        <Typography variant='h1' className="text-2xl text-red-500 mb-2">Financial Model</Typography>
                        <br />
                        <Typography className='lg:text-lg md:text-base text-sm' >Bringing you the opportunity to own a peice of paradise located in Mandrem, Goa. This stunning property offers the ultimate comfort and style, with its spacious interiors. modern amenties and breathtaking views. Easily accessible from the most pristine and popular beaches of Goa, the location is just one of the top features of this villa. This 4 BHK villa comes with a private pool and car park while also being full furnished and maintained</Typography>
                        <Typography className='lg:text-lg md:text-base text-sm' ></Typography>


                        <div className="relative overflow-x-auto">

                        </div>


                    </div>

                    <div className="lg:w-3/4 rounded overflow-x-auto shadow-lg shadow-gray-600 card">
                        <div className="px-6 py-4">
                            <div className="font-bold text-xl">Location Highlights</div>
                        </div>
                        <iframe src="https://www.google.com/maps/embed?pb=!1m14!1m12!1m3!1d13834.255347225278!2d74.79663764409774!3d13.34364319791093!2m3!1f0!2f0!3f0!3m2!1i1024!2i768!4f13.1!5e0!3m2!1sen!2sin!4v1699276791486!5m2!1sen!2sin" allowFullScreen={true} width={"100%"} height={"500"} loading="lazy" referrerPolicy="no-referrer-when-downgrade"></iframe>

                    </div>
                </div>

            </div>
            <Footer />
        </div>
    )
}
